Testene henter testdata fra filer, finner size i Contant-klassen og e…
navikt/pale-2 pull request #56
Opened 2023-01-04 09:30 UTC by oysbak

…n skrivefeil

2023-01-04 09:47 UTC, MikAoJk commented on src/test/kotlin/no/nav/syfo/service/VirusScanServiceTest.kt
> +        val contentImage = java.io.File("src/test/resources/doctor.jpeg").readBytes().contentToString()
Kanskje hatt ein metode som heter ut innholdet i fil og returenen string:

`fun getFileAsString(filePath: String) = String(Files.readAllBytes(Paths.get(filePath)), StandardCharsets.UTF_8)
`

2023-01-04 09:50 UTC, MikAoJk commented
Ser også at det er ein konflikt med master branchen, så anbefaler at du drar in master branch i din

2023-01-04 09:51 UTC, MikAoJk commented
Husk å post link til pr i kanelen #team-sykmelding-utvikling

https://github.com/navikt/pale-2/pull/56

2023-01-04 12:23 UTC, andreasDev commented on src/main/kotlin/no/nav/syfo/vedlegg/model/Vedlegg.kt
> +    val size = this.content.contentLength
om disse ikke brukes til noe så kan de fjernes

2023-01-04 12:23 UTC, andreasDev commented on src/main/kotlin/no/nav/syfo/vedlegg/model/Vedlegg.kt
> +    val contentLength = content.length
samme her

2023-01-04 12:50 UTC, MikAoJk commented on src/test/kotlin/no/nav/syfo/service/VirusScanServiceTest.kt
> +        val content = java.io.File("src/test/resources/doctor.jpeg").readBytes().contentToString()
Bildet er ikkje base Base64 encodet, så her kan testdatene bli litt missvisende

2023-01-05 09:47 UTC, tiafiring commented on src/test/kotlin/no/nav/syfo/service/VirusScanServiceTest.kt
> +import java.util.*
Vi pleier ikke bruke stjerneimports, så det kan hende det er lurt at du endrer i intellij-settingene dine så du slipper import-diff hver gang du endrer en fil 😅

2023-01-05 09:59 UTC, tiafiring commented on src/test/kotlin/no/nav/syfo/service/VirusScanServiceTest.kt
>              val vedleggContainsVirus =
Jeg får ikke kommentert på linjen med assertEquals, men jeg tror expected og actual har byttet plass. Supert om du kan bytte om så det blir riktig når du først er inne her 😊

2023-01-05 10:00 UTC, tiafiring commented on src/test/kotlin/no/nav/syfo/service/VirusScanServiceTest.kt
>              assertEquals(vedleggContainsVirus, true)
Her tror jeg også at expected og actual har byttet plass 🙈

2023-01-05 12:11 UTC, MikAoJk requested changes

2023-01-05 12:11 UTC, MikAoJk commented on src/test/kotlin/no/nav/syfo/service/VirusScanServiceTest.kt
> +        val contentImage = getFileContentAsString("src/test/resources/doctor.jpeg")
Eg ville nok ha laget ein ny metode noe slik:
`fun getFileContentAsByteArray(filepath: String): ByteArray {
        return Files.readAllBytes(Paths.get(filepath))
    }`
Får å så encode det til Base64 slik: `val contentImage = Base64.getEncoder().encode(getFileContentAsByteArray("src/test/resources/doctor.jpeg")).toString()`

2023-01-05 12:35 UTC, oysbak commented on src/test/kotlin/no/nav/syfo/service/VirusScanServiceTest.kt
>              val vedleggContainsVirus =
Ja, jeg har sett dette flere steder. Skal rydde

2023-01-05 12:36 UTC, oysbak commented on src/test/kotlin/no/nav/syfo/service/VirusScanServiceTest.kt
> +        val contentImage = getFileContentAsString("src/test/resources/doctor.jpeg")
Ok, så bygge om så all encoding/decoding foregår i koden

2023-01-05 12:52 UTC, oysbak commented on src/test/kotlin/no/nav/syfo/service/VirusScanServiceTest.kt
> +        val contentImage = java.io.File("src/test/resources/doctor.jpeg").readBytes().contentToString()
Gjort, men med UTF_16

2023-01-05 13:03 UTC, oysbak commented on src/main/kotlin/no/nav/syfo/vedlegg/model/Vedlegg.kt
> +    val size = this.content.contentLength
OK

2023-01-05 13:06 UTC, oysbak commented on src/test/kotlin/no/nav/syfo/service/VirusScanServiceTest.kt
> +import java.util.*
Ja, spurte Andreas og Karl om det i går og de sa det samme. Trodde jeg hadde endret denne

2023-01-05 13:45 UTC, MikAoJk commented on src/test/kotlin/no/nav/syfo/service/VirusScanServiceTest.kt
> +        val contentImage = getFileContentAsString("src/test/resources/doctor.jpeg")
Ja eg tenker det kan være like greit

2023-01-05 21:55 UTC, MikAoJk approved these changes

2023-01-06 12:15 UTC, andreasDev approved these changes

2023-01-06 13:06 UTC, merged